---
- hosts: 127.0.0.1
  tasks:
    - name: create new vm from template
      vmware_guest:
        hostname: 192.168.0.103
        username: administrator@vsphere.local
        password: reset4U$
        validate_certs: False
        name: jenkins-server
        template: Template-Server
        datacenter: Datacenter1
        folder: "/"  
        state: poweredon
        wait_for_ip_address: yes
     
    - name: Set authorized key for root user copying it from current user
      authorized_key:
        user: root
        state: present
        key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}" 
        tag: key
      
